source "https://rubygems.org"


gem 'sinatra', git: 'git@github.com:sinatra/sinatra.git'
gem "activerecord"
gem "sqlite3"
gem "mysql2"
gem "active_record_migrations"
gem 'kaminari', require: %w( kaminari kaminari/hooks kaminari/sinatra)
gem "padrino-helpers"

#gem "puma"

group :test do
  gem "rspec"
  gem "fabrication"
  gem "database_cleaner"
end

group :development do
  gem "better_errors"
  gem 'sinatra-contrib'
  gem "faker"
 # gem "shotgun"
end

