# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b5cbf16cfa3ab696b72395a261a1d9acecf2e171c0cabcb7e4aea2180baef84c176eb9defcb31125e1f99f10e4abf1d38da21830b98d20a39e6abfc98a68d6f

test:
  secret_key_base: 037dedcfe989625353216496d0e3c18bc83626e09763ff7cb1c63df6091c05052d9113c10ae0a0b17028e6e9d8f237110b701416483bc65c34156b02b661f9f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 037dedcfe989625353216496d0e3c18bc83626e09763ff7cb1c63df6091c05052d9113c10ae0a0b17028e6e9d8f237110b701416483bc65c34156b02b661f9f3
